# Generated by CMake 2.8.10.1

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target iDynTree
ADD_LIBRARY(iDynTree STATIC IMPORTED)

# Make sure the targets which have been exported in some other 
# export set exist.

# Import target "iDynTree" for configuration ""
SET_PROPERTY(TARGET iDynTree APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(iDynTree PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpcar;yarp_bayer;YARP_name;YARP_init;orocos-kdl;/usr/local/lib/libkdl_codyco.so"
  IMPORTED_LOCATION_NOCONFIG "/home/pegua/src/codyco/src/iDynTree/cmake/libiDynTree.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.8.10.1

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target iDynTree
ADD_LIBRARY(iDynTree STATIC IMPORTED)

# Make sure the targets which have been exported in some other 
# export set exist.

# Import target "iDynTree" for configuration ""
SET_PROPERTY(TARGET iDynTree APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(iDynTree PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpcar;yarp_bayer;YARP_name;YARP_init;orocos-kdl;/usr/local/lib/libkdl_codyco.so"
  IMPORTED_LOCATION_NOCONFIG "/home/pegua/src/codyco/src/iDynTree/cmake/libiDynTree.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
