function generateFilesForWalkPlayer( input_file, ts , outputDir)
% generateFilesForWalkPlayer Takes trajectory files generated by icub_walk and splits it into
% the files necessary by walkPlayer

dataFromFile = csvread(input_file);

% Prepare torso data
torsoDataMat = prepareDataForTxt(dataFromFile(:,end-2:end), ts);
formatSpecTorso = '%5i %6.5f %10.5f %10.5f %10.5f\n';
writeToTxt([outputDir '/icub_walk_seq_torso'],torsoDataMat,formatSpecTorso);

% Prepare left leg data
leftLegDataMat = prepareDataForTxt(dataFromFile(:,1:6), ts);
formatSpecLegs = '%5i %6.5f %10.5f %10.5f %10.5f %10.5f %10.5f %10.5f\n';
writeToTxt([outputDir '/icub_walk_seq_left'],leftLegDataMat,formatSpecLegs);

% Prepare right leg data
rightLegDataMat = prepareDataForTxt(dataFromFile(:,7:12), ts);
writeToTxt([outputDir '/icub_walk_seq_right'],rightLegDataMat,formatSpecLegs);

end

